spring:
  application:
    name: demo
  datasource:
    username: root
    password: 111
    url:  jdbc:mysql://localhost:3306/excel
    driver-class-name: com.mysql.jdbc.Driver


server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.demo.dao: debug

